---
- name: "Installing and configuring LAMP stack with WordPress"
  hosts: client_servers
  become: true
  vars_files:
    - variables

  tasks:
    - name: "Installing packages (Apache, PHP, MariaDB)"
      yum:
        name: "{{ packages }}"
        state: present
        
    - name: "Creating configuration file"
      template:
        src: "./httpd.conf.tmpl"
        dest: "/etc/httpd/conf/httpd.conf"

    - name: "Creating virtual host for {{ hostname }}"
      template:
        src: "./virtualhost.conf.tmpl"
        dest: "/etc/httpd/conf.d/{{ hostname }}.conf"
        owner: "{{ httpd_owner }}" 
        group: "{{ httpd_group }}"

    - name: "Creating Docroot for {{ hostname }}"
      file:
        path: "/var/www/html/{{ hostname }}"
        state: directory
        owner: "{{ httpd_owner }}"
        group: "{{ httpd_group }}"

    - name: "Restarting web and PHP services"
      service: 
        name: "{{ item }}"
        state: restarted
        enabled: true
      loop:
        - httpd
        - php-fpm   

    - name: "Installing Python module to connect with MariaDB" 
      pip:
        name: "PyMySQL"
        state: present

    - name: "Starting MariaDB service"
      service:
        name: "mariadb"
        state: restarted
        enabled: true

    - name: "Resetting DB root password"
      ignore_errors: true
      community.mysql.mysql_user:
        login_user: root
        login_password: ""
        user: "root"
        password: "{{ root_password }}"
        host_all: true
        login_unix_socket: /var/lib/mysql/mysql.sock

    - name: "Removing anonymous users"
      community.mysql.mysql_user:
        login_user: root
        login_password: "{{ root_password }}"
        name: ""
        host_all: true
        state: absent
        login_unix_socket: /var/lib/mysql/mysql.sock

    - name: "Creating application DB"
      community.mysql.mysql_db:
        login_user: root
        login_password: "{{ root_password }}"
        name: "{{ db_name }}"
        state: present 
        login_unix_socket: /var/lib/mysql/mysql.sock

    - name: "Creating a user for application" 
      community.mysql.mysql_user:
        login_user: root
        login_password: "{{ root_password }}"
        user: "{{ db_user }}"
        password: "{{ db_password }}" 
        host: "%"
        priv: "{{ db_name }}.*:ALL"
        login_unix_socket: /var/lib/mysql/mysql.sock

    - name: "Downloading WordPress site contents"
      get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: "/tmp/wordpress.tar.gz"

    - name: "Extracting WordPress site contents"
      unarchive:
        src: "/tmp/wordpress.tar.gz"
        dest: "/tmp/"
        remote_src: true

    - name: "Copy WordPress contents to Doc root"
      copy:
        src: "/tmp/wordpress/"
        dest: "/var/www/html/{{ hostname }}"
        remote_src: yes
        owner: "{{ httpd_owner }}"
        group: "{{ httpd_group }}"

    - name: "Creating wp-config file"
      template:
        src: "./wp-config.php.tmpl"
        dest: "/var/www/html/{{ hostname }}/wp-config.php"
        owner: "{{ httpd_owner }}"
        group: "{{ httpd_group }}"
